version: '3.8'

services:
  db:
    image: postgres:17.5
    container_name: InternetShopDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
      POSTGRES_DB: internetshop

  server:
    image: internet_shop_backend:latest
    container_name: InternetShopBackend
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://InternetShopDB:5432/internetshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5432

  frontend:
    container_name: InternetShopFrontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:8080